// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdixdappzasnclojviaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkaXhkYXBwemFzbmNsb2p2aWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0NDc5NDEsImV4cCI6MjA0OTAyMzk0MX0.UfuWqrVzWF53De8R72FTnWssXJUtO81GTqHO6WoB1Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);